# Use the official Python image
FROM python:3.11

# Set working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Run the script
CMD ["python", "app.py"]